### ISSUE TITLE
i18n Unit Tests & Properties Files

### ISSUE THREAD

**Issue by akelsch** [akelsch/car-rental#7]
siehe PR #5 

@lraubuch bitte Unit Tests nachreichen

Außerdem: wieso liegen die properties Dateien nicht im resources Ordner?

**Comment by lraubuch** [comment]
Ja hatte das nur schnell machen wollen damit nicht jeder später umstellen muss.
Werde das gleich machen.

**Comment by lraubuch** [comment]
Habe gerade nachgeschaut und es ist anscheinend nicht möglich ein Verzeichnis zu referenzieren, das über dem root Verzeichnnis liegt was in diesem Fall src/main/java ist. Man kann deshalb die Dateien nicht unter src/main/resources packen. Ich schaue noch ob ich etwas finde aber bisher habe ich keine Projekte gefunden die sie nicht unter dem Package speichern wie ich es getan habe -.-

**Comment by akelsch** [comment]
Problem gelöst 😄

Quelle: https://draeger-it.blog/javafx-implementierung-des-resourcebundle/

Gemerged in #8
